const translations = {
  it: {
    nav:{about:"Chi sono",lessons:"Lezioni",method:"Come funziona",contact:"Contatti"},
    hero:{eyebrow:"Lezioni 100% online",title:"Impara una lingua.<br><em>Fai un passo avanti.</em>",text:"Ripetizioni personalizzate di italiano, tedesco, inglese e spagnolo, pensate per aiutarti a raggiungere i tuoi obiettivi con metodo e sicurezza.",cta:"Prenota la prima lezione gratuita",secondary:"Scopri le lezioni",languages:"lingue",online:"online",free:"lezione gratuita"},
    orbit:{german:"Tedesco",english:"Inglese",spanish:"Spagnolo",italian:"Italiano"},
    about:{label:"CHI SONO",title:"Un aiuto concreto per sentirti più sicuro/a nelle lingue.",photo:"La tua foto",photoHint:"Inserisci qui un'immagine professionale",badgeTitle:"Un percorso su misura",badgeText:"Obiettivi, ritmo e metodo pensati per te.",p1:"Ciao! Sono Dalila e accompagno studenti e adulti nello studio delle lingue con lezioni individuali, pratiche e personalizzate.",p2:"Partiamo dal tuo livello e dai tuoi obiettivi: recuperare una materia, preparare una verifica, migliorare la conversazione o semplicemente acquistare più sicurezza.",cred1:"Lezioni individuali",cred2:"Materiale personalizzato",cred3:"Approccio pratico",cred4:"Orari flessibili"},
    lessons:{label:"LE LINGUE",title:"Scegli la lingua,<br><em>inizia il tuo percorso.</em>",intro:"Una lezione non dovrebbe essere uguale per tutti. Il programma viene adattato al tuo livello e alle tue esigenze."},
    cards:{italian:"Grammatica, conversazione, comprensione e supporto scolastico.",german:"Dalla grammatica alla conversazione, con esercizi mirati.",english:"Speaking, vocabulary, grammar e preparazione alle verifiche.",spanish:"Pronuncia, conversazione, grammatica e comprensione.",cta:"Scopri →"},
    method:{label:"COME FUNZIONA",title:"Semplice. Personale. Online.",intro:"Niente percorsi complicati: ci conosciamo, definiamo l'obiettivo e costruiamo insieme il percorso."},
    steps:{oneTitle:"Mi contatti",oneText:"Raccontami quale lingua vuoi migliorare e di cosa hai bisogno.",twoTitle:"Ci conosciamo",twoText:"La prima lezione conoscitiva è gratuita e senza impegno.",threeTitle:"Definiamo il piano",threeText:"Stabiliamo obiettivi, ritmo e contenuti delle lezioni.",fourTitle:"Iniziamo",fourText:"Ti accompagno passo dopo passo verso i tuoi risultati."},
    free:{label:"PRIMO PASSO",title:"La prima lezione conoscitiva è gratuita.",text:"Conosciamoci, parliamo dei tuoi obiettivi e vediamo insieme da dove partire.",cta:"Richiedi la lezione gratuita"},
    contact:{label:"CONTATTI",title:"Parliamo del tuo prossimo obiettivo.",text:"Hai domande? Scrivimi senza impegno. Ti risponderò con tutte le informazioni sulle lezioni e sulla disponibilità.",emailLabel:"EMAIL",note:"Le lezioni possono essere svolte in italiano, tedesco, inglese o spagnolo."},
    form:{name:"Nome",namePlaceholder:"Il tuo nome",email:"Email",language:"Lingua di interesse",message:"Messaggio",messagePlaceholder:"Scrivimi qualche informazione sulle tue esigenze...",submit:"Invia richiesta",disclaimer:"Il pulsante apre il tuo programma email predefinito. Nessun dato viene inviato a un server."},
    footer:{rights:"Tutti i diritti riservati."}
  },
  de: {
    nav:{about:"Über mich",lessons:"Unterricht",method:"So funktioniert's",contact:"Kontakt"},
    hero:{eyebrow:"100% Online-Unterricht",title:"Lerne eine Sprache.<br><em>Mach den nächsten Schritt.</em>",text:"Individueller Unterricht in Italienisch, Deutsch, Englisch und Spanisch – passend zu deinen Zielen und deinem Lerntempo.",cta:"Kostenlose Probestunde buchen",secondary:"Unterricht entdecken",languages:"Sprachen",online:"online",free:"kostenlose Stunde"},
    orbit:{german:"Deutsch",english:"Englisch",spanish:"Spanisch",italian:"Italienisch"},
    about:{label:"ÜBER MICH",title:"Konkrete Unterstützung, damit du dich in Sprachen sicherer fühlst.",photo:"Dein Foto",photoHint:"Hier ein professionelles Foto einfügen",badgeTitle:"Individueller Lernweg",badgeText:"Ziele, Tempo und Methode passend zu dir.",p1:"Hallo! Ich bin [Name] und unterstütze Schüler:innen und Erwachsene mit individuellem, praktischem und persönlichem Sprachunterricht.",p2:"Wir starten bei deinem Niveau und deinen Zielen: Schulstoff aufholen, eine Prüfung vorbereiten, Konversation verbessern oder einfach mehr Sicherheit gewinnen.",cred1:"Einzelunterricht",cred2:"Individuelles Material",cred3:"Praxisnaher Ansatz",cred4:"Flexible Zeiten"},
    lessons:{label:"SPRACHEN",title:"Wähle deine Sprache,<br><em>starte deinen Weg.</em>",intro:"Keine Unterrichtsstunde ist gleich. Inhalte und Tempo werden an dein Niveau und deine Bedürfnisse angepasst."},
    cards:{italian:"Grammatik, Konversation, Verständnis und schulische Unterstützung.",german:"Von Grammatik bis Konversation mit gezielten Übungen.",english:"Speaking, Wortschatz, Grammatik und Prüfungsvorbereitung.",spanish:"Aussprache, Konversation, Grammatik und Verständnis.",cta:"Entdecken →"},
    method:{label:"SO FUNKTIONIERT'S",title:"Einfach. Persönlich. Online.",intro:"Kein komplizierter Ablauf: Wir lernen uns kennen, definieren dein Ziel und gestalten gemeinsam deinen Weg."},
    steps:{oneTitle:"Du kontaktierst mich",oneText:"Erzähl mir, welche Sprache du verbessern möchtest und wobei du Unterstützung brauchst.",twoTitle:"Wir lernen uns kennen",twoText:"Die erste Kennenlernstunde ist kostenlos und unverbindlich.",threeTitle:"Wir planen",threeText:"Wir legen Ziele, Tempo und Inhalte des Unterrichts fest.",fourTitle:"Wir starten",fourText:"Ich begleite dich Schritt für Schritt zu deinen Zielen."},
    free:{label:"ERSTER SCHRITT",title:"Die erste Kennenlernstunde ist kostenlos.",text:"Lernen wir uns kennen, sprechen wir über deine Ziele und finden wir gemeinsam den besten Startpunkt.",cta:"Kostenlose Stunde anfragen"},
    contact:{label:"KONTAKT",title:"Sprechen wir über dein nächstes Ziel.",text:"Du hast Fragen? Schreib mir unverbindlich. Ich sende dir alle Informationen zu Unterricht und Verfügbarkeit.",emailLabel:"E-MAIL",note:"Der Unterricht kann auf Italienisch, Deutsch, Englisch oder Spanisch stattfinden."},
    form:{name:"Name",namePlaceholder:"Dein Name",email:"E-Mail",language:"Gewünschte Sprache",message:"Nachricht",messagePlaceholder:"Erzähl mir kurz von deinen Bedürfnissen...",submit:"Anfrage senden",disclaimer:"Der Button öffnet dein Standard-E-Mail-Programm. Es werden keine Daten an einen Server gesendet."},
    footer:{rights:"Alle Rechte vorbehalten."}
  },
  en: {
    nav:{about:"About me",lessons:"Lessons",method:"How it works",contact:"Contact"},
    hero:{eyebrow:"100% online lessons",title:"Learn a language.<br><em>Take the next step.</em>",text:"Personalized lessons in Italian, German, English and Spanish, designed around your goals, level and learning pace.",cta:"Book a free first lesson",secondary:"Explore lessons",languages:"languages",online:"online",free:"free lesson"},
    orbit:{german:"German",english:"English",spanish:"Spanish",italian:"Italian"},
    about:{label:"ABOUT ME",title:"Practical support to help you feel more confident with languages.",photo:"Your photo",photoHint:"Add a professional photo here",badgeTitle:"A tailored path",badgeText:"Goals, pace and method designed for you.",p1:"Hi! I'm [Name], and I support students and adults with practical, personalized one-to-one language lessons.",p2:"We start from your level and your goals: catching up at school, preparing for a test, improving conversation or simply building confidence.",cred1:"One-to-one lessons",cred2:"Personalized material",cred3:"Practical approach",cred4:"Flexible scheduling"},
    lessons:{label:"LANGUAGES",title:"Choose your language,<br><em>start your journey.</em>",intro:"Lessons shouldn't be one-size-fits-all. Content and pace are adapted to your level and needs."},
    cards:{italian:"Grammar, conversation, comprehension and school support.",german:"From grammar to conversation, with focused exercises.",english:"Speaking, vocabulary, grammar and test preparation.",spanish:"Pronunciation, conversation, grammar and comprehension.",cta:"Discover →"},
    method:{label:"HOW IT WORKS",title:"Simple. Personal. Online.",intro:"No complicated process: we meet, define your goal and build the right path together."},
    steps:{oneTitle:"Get in touch",oneText:"Tell me which language you want to improve and what you need help with.",twoTitle:"Meet & connect",twoText:"The first introductory lesson is free and comes with no obligation.",threeTitle:"Build the plan",threeText:"We define goals, pace and lesson content together.",fourTitle:"Let's begin",fourText:"I'll support you step by step towards your goals."},
    free:{label:"FIRST STEP",title:"Your first introductory lesson is free.",text:"Let's meet, talk about your goals and find the best place to start.",cta:"Request the free lesson"},
    contact:{label:"CONTACT",title:"Let's talk about your next goal.",text:"Have questions? Send me a message with no obligation. I'll reply with information about lessons and availability.",emailLabel:"EMAIL",note:"Lessons can be held in Italian, German, English or Spanish."},
    form:{name:"Name",namePlaceholder:"Your name",email:"Email",language:"Language of interest",message:"Message",messagePlaceholder:"Tell me a little about what you need...",submit:"Send request",disclaimer:"The button opens your default email application. No data is sent to a server."},
    footer:{rights:"All rights reserved."}
  },
  es: {
    nav:{about:"Sobre mí",lessons:"Clases",method:"Cómo funciona",contact:"Contacto"},
    hero:{eyebrow:"Clases 100% online",title:"Aprende un idioma.<br><em>Da el siguiente paso.</em>",text:"Clases personalizadas de italiano, alemán, inglés y español, adaptadas a tus objetivos, nivel y ritmo de aprendizaje.",cta:"Reserva la primera clase gratis",secondary:"Descubre las clases",languages:"idiomas",online:"online",free:"clase gratis"},
    orbit:{german:"Alemán",english:"Inglés",spanish:"Español",italian:"Italiano"},
    about:{label:"SOBRE MÍ",title:"Un apoyo práctico para que te sientas más seguro/a con los idiomas.",photo:"Tu foto",photoHint:"Añade aquí una foto profesional",badgeTitle:"Un camino a tu medida",badgeText:"Objetivos, ritmo y método pensados para ti.",p1:"¡Hola! Soy [Nombre] y acompaño a estudiantes y adultos con clases individuales, prácticas y personalizadas.",p2:"Partimos de tu nivel y tus objetivos: recuperar contenidos, preparar un examen, mejorar la conversación o simplemente ganar confianza.",cred1:"Clases individuales",cred2:"Material personalizado",cred3:"Enfoque práctico",cred4:"Horarios flexibles"},
    lessons:{label:"IDIOMAS",title:"Elige tu idioma,<br><em>empieza tu camino.</em>",intro:"Cada clase es diferente. El contenido y el ritmo se adaptan a tu nivel y a tus necesidades."},
    cards:{italian:"Gramática, conversación, comprensión y apoyo escolar.",german:"De la gramática a la conversación, con ejercicios específicos.",english:"Speaking, vocabulario, gramática y preparación de exámenes.",spanish:"Pronunciación, conversación, gramática y comprensión.",cta:"Descubre →"},
    method:{label:"CÓMO FUNCIONA",title:"Sencillo. Personal. Online.",intro:"Sin procesos complicados: nos conocemos, definimos el objetivo y construimos juntos el camino."},
    steps:{oneTitle:"Me contactas",oneText:"Cuéntame qué idioma quieres mejorar y qué necesitas.",twoTitle:"Nos conocemos",twoText:"La primera clase de presentación es gratuita y sin compromiso.",threeTitle:"Creamos el plan",threeText:"Definimos objetivos, ritmo y contenidos de las clases.",fourTitle:"Empezamos",fourText:"Te acompaño paso a paso hacia tus objetivos."},
    free:{label:"PRIMER PASO",title:"La primera clase de presentación es gratis.",text:"Nos conocemos, hablamos de tus objetivos y vemos juntos por dónde empezar.",cta:"Solicita la clase gratis"},
    contact:{label:"CONTACTO",title:"Hablemos de tu próximo objetivo.",text:"¿Tienes preguntas? Escríbeme sin compromiso. Te responderé con toda la información sobre las clases y la disponibilidad.",emailLabel:"EMAIL",note:"Las clases pueden realizarse en italiano, alemán, inglés o español."},
    form:{name:"Nombre",namePlaceholder:"Tu nombre",email:"Email",language:"Idioma de interés",message:"Mensaje",messagePlaceholder:"Cuéntame brevemente qué necesitas...",submit:"Enviar solicitud",disclaimer:"El botón abre tu aplicación de correo predeterminada. No se envían datos a un servidor."},
    footer:{rights:"Todos los derechos reservados."}
  }
};
